spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:billing?createDatabaseIfNotExist=true;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    hikari:
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
logging:
  level:
    web: DEBUG
    root: DEBUG
jwt:
  secretKey: baiksdev@2024
  jwtValidityPeriodInMilliSecs: 6000000